production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  host: dpg-d9lk0hoae00c73ait4kg-a.oregon-postgres.render.com
  port: 5432
  database: webpagtrading_development
  username: nithyanand
  password: PuYA2bywpOxNh73Qtt8vFWYNJghVNjki