default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: webpagtrading_development
  username: nithyanand
  password: 123456789
  host: localhost
  port: 5432

test:
  <<: *default
  database: webpagtrading_test

production:
  <<: *default
  database: webpagtrading_development
  username: nithyanand
  password: PuYA2bywpOxNh73Qtt8vFWYNJghVNjki
  host: dpg-d9lk0hoae00c73ait4kg-a
  port: 5432
