default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: webpagtrading_development
  username: nithyanand
  password: 123456789
  host: localhost
  port: 5432

test:
  <<: *default
  database: webpagtrading_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
